# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "janoamaral/tokyo-night-tmux"


set -g @tokyo-night-tmux_theme storm    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @tokyo-night-tmux_zoom_id_style fsquare # dsquare | hsquare | digital

# Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 1
set -g @tokyo-night-tmux_time_format 24H

#path
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'

run '~/.tmux/plugins/tpm/tpm'

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
setw -g mouse on

# statusbar
set -g status-position bottom
set -g status-justify left

set -g status-left ''
set -g status-left-length 10
set -g status-right-length 50

# Split panes horizontally using the current path
bind % split-window -h -c "#{pane_current_path}"

# Split panes vertically using the current path
bind '"' split-window -v -c "#{pane_current_path}"

