"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$docker_context\
$conda\
$cmd_duration\
$battery\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_dark_blue = '#05A2EC'
color_fg0 = '#fbf1c7'
color_bg2 = '#000'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_yellow = '#d79921'


[username]
show_always = true
style_user = "italic color_purple"
style_root = "italic color_blue"
format = '[ $user ]($style)'

[directory]
style = "color_dark_blue"
format = "[$path ◯]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncation_symbol = "../"
read_only = " ■"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = ""
style = ""
format = '[[ $symbol $branch ](fg:color_aqua )]($style)'

[git_status]
style = ""
#format = '[[($all_status$ahead_behind ▶)](color_orange )]($style)'
format = """([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▲│[${count}](bold white)│](italic green)"
behind = "[▽│[${count}](bold white)│](italic red)"
diverged = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-mmagenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◦◫◦](italic white)"
modified = "[●◦](italic yellow)"
staged = "[■┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"


[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = ""
#style = "bg:color_bg3"
#format = '[[ $symbol( $environment) ](fg:#83a598 )]'
format = '[ $symbol( $environment) ](fg:#83a598 )'


[line_break]
disabled = false

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "[█](italic green)"
charging_symbol = "[↑](italic green)"
discharging_symbol = "[↓](italic)"
unknown_symbol = "[░](italic)"
empty_symbol = "[▃](italic red)"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[character]
disabled = false
success_symbol = '[◉](bold fg:color_green)'
error_symbol = '[◯](bold red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
min_time = 500
format = "[ ◇ $duration ](fg:italic yellow )"
