#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#5294E2'
BSPWM_NBC='#141c21'
BSPWM_ABC='#696ebf'
BSPWM_PFC='#819400'

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='8'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
# bspc monitor -d '' '' '' '' '' '' '' ''
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX'
## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# Kill if already running
# killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc
killall -9 picom sxhkd dunst polybar

sleep 5
# Lauch keybindings daemon
sxhkd -c ~/.config/bspwm/sxhkdrc

# Restore wallpaper
feh --bg-fill /usr/share/backgrounds/wallpaper/BlueLady.png &

# polybar
polybar &
picom -b
dunst &
